feat: aaa

diff --git a/.github/workflows/.release.yml b/.github/workflows/.release.yml
--- a/.github/workflows/.release.yml
+++ b/.github/workflows/.release.yml
@@ -14,9 +14,11 @@ jobs:
     env:
       # Store the release type from workflow input to reuse it across steps
       RELEASE_TYPE: ${{ github.event.inputs.release-type }}
+
     permissions:
-        contents: write
-        actions: write
+      contents: write
+      actions: write
+
     steps:
       - name: Checkout source code
         uses: actions/checkout@v3
@@ -32,6 +34,14 @@ jobs:
       # Clean dist directory
       - name: Clean dist directory
         run: rm -rf dist/*
+
+      # Verify dist directory is clean
+      - name: Verify dist directory is clean
+        run: |
+          if [ -n "$(ls -A dist)" ]; then
+            echo "Error: dist directory not clean"
+            exit 1
+          fi
 
       # Install Node.js dependencies, including release-it
       - name: Install Node.js dependencies
@@ -56,7 +66,6 @@ jobs:
           TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
         continue-on-error: false
-
 
       # If the release step fails, print and upload the NPM error log
       - name: Print NPM error log
